name: Deploy to Forpsi

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare known_hosts (avoid prompt)
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: SSH to server and deploy
        uses: appleboy/ssh-action@v1.2.0
        with:
          host:     ${{ secrets.SSH_HOST }}   # 80.211.223.9
          username: ${{ secrets.SSH_USER }}   # root
          key:      ${{ secrets.SSH_KEY }}    # privátní klíč pro přístup z Actions na server
          script: |
            set -euxo pipefail

            # 1) připravit /root/.ssh/known_hosts pro GitHub (aby git fetch nechtěl potvrzení)
            mkdir -p /root/.ssh
            ssh-keyscan -H github.com >> /root/.ssh/known_hosts || true
            chmod 700 /root/.ssh
            chmod 600 /root/.ssh/known_hosts

            # 2) repo – naklonovat pokud chybí, jinak fetch/reset na main
            if [ ! -d /root/anime-cloud/.git ]; then
              # nastav si URL repozitáře
              git clone git@github.com:Meiyueh/anime-cloud.git /root/anime-cloud
            fi

            cd /root/anime-cloud
            # pro jistotu přepnout na SSH URL (server používá svojí "deploy key")
            git remote set-url origin git@github.com:Meiyueh/anime-cloud.git
            git fetch origin main
            git reset --hard origin/main

            # 3) (volitelně) doinstaluj závislosti, pokud se requirements.txt změnil
            if [ -f requirements.txt ]; then
              /opt/animecloud/venv/bin/pip install -r requirements.txt
            fi

            # 4) restart služby
            systemctl daemon-reload || true
            systemctl restart animecloud
            systemctl --no-pager --full status animecloud | sed -n '1,40p'

            # 5) krátký health-check lokálně na serveru (běží přes 127.0.0.1, tj. obejde firewall/DNS)
            curl -fsS -I http://127.0.0.1:8080/index.html | sed -n "1,12p" || true
