name: Deploy to VPS

on:
  push:
    branches: [ main ]   # uprav, pokud deployuješ z jiné větve

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_USER: ${{ secrets.SSH_USER }}
      SSH_DEST: ${{ secrets.SSH_DEST }}   # když nedefinuješ, použijeme /root/anime-cloud níž v shellu
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Start ssh-agent and add private key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add server to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H "$SSH_HOST" >> ~/.ssh/known_hosts

      - name: Show what will be sent (local tree)
        run: |
          echo "PWD=$(pwd)"
          git status --porcelain || true
          ls -la

      - name: Rsync files to server (with verbose log)
        run: |
          set -euo pipefail
          DEST="${SSH_DEST:-/root/anime-cloud}"   # <-- fallback tady, v shellu (správně)
          echo "Deploying to $SSH_USER@$SSH_HOST:$DEST/"
          # -a = archive, -v = verbose, -z = compression, --delete = smazat na cíli co v repu není
          # --itemize-changes = vypíše, co přesně mění
          rsync -avz --delete --itemize-changes \
            --exclude ".git/" \
            --exclude ".github/" \
            ./ "$SSH_USER@$SSH_HOST:$DEST/"

      - name: Verify files on server
        run: |
          DEST="${SSH_DEST:-/root/anime-cloud}"
          ssh "$SSH_USER@$SSH_HOST" "echo 'Listing $DEST'; ls -la $DEST | sed -n '1,120p'"

      - name: Restart service
        run: |
          ssh "$SSH_USER@$SSH_HOST" \
            "sudo systemctl restart animecloud && sudo systemctl status --no-pager --lines=3 animecloud || true"
