name: Deploy to VPS

on:
  push:
    branches: ["main"]
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout (not strictly needed, but fine)
        uses: actions/checkout@v4

      - name: SSH to server and deploy
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          # port: ${{ secrets.SSH_PORT }}
          script: |
            set -euo pipefail

            echo "==> Ensure repo ownership & git safe.directory"
            chown -R root:root /root/anime-cloud || true
            git config --global --add safe.directory /root/anime-cloud || true

            echo "==> Pull latest code"
            cd /root/anime-cloud
            git fetch --all
            git checkout main || true
            git reset --hard origin/main

            echo "==> Ensure Python venv & deps (/opt/anime-cloud/.venv)"
            if [ ! -d /opt/anime-cloud/.venv ]; then
              mkdir -p /opt/anime-cloud
              python3 -m venv /opt/anime-cloud/.venv
            fi
            /opt/anime-cloud/.venv/bin/python -m pip install -U pip
            /opt/anime-cloud/.venv/bin/pip install -r requirements.txt

            echo "==> Check server-side secrets in /etc/anime-cloud"
            if [ ! -f /etc/anime-cloud/gcs-key.json ]; then
              echo "ERROR: /etc/anime-cloud/gcs-key.json missing!"; exit 2
            fi
            # .env je volitelný (EnvironmentFile=-...), jen upozorníme:
            if [ ! -f /etc/anime-cloud/.env ]; then
              echo "WARN: /etc/anime-cloud/.env not found (service may rely on unit env only)"
            fi
            chmod 600 /etc/anime-cloud/gcs-key.json || true
            chmod 600 /etc/anime-cloud/.env || true

            echo "==> Restart service"
            systemctl daemon-reload || true
            systemctl restart animecloud

            echo "==> Healthcheck"
            ok=false
            for i in {1..20}; do
              if curl -fsS -I http://127.0.0.1:8080/index.html >/dev/null; then
                ok=true; echo "Service is UP"; break
              fi
              echo "Waiting... ($i/20)"; sleep 2
            done
            if [ "$ok" != true ]; then
              echo "Service didn't start. Recent logs:"
              journalctl -u animecloud -n 200 --no-pager || true
              exit 7
            fi

            echo "==> Done"
