name: Deploy (rsync -> restart)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Write SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/animecloud_key
          chmod 600 ~/.ssh/animecloud_key

      - name: Rsync files to server
        run: |
          RSYNC_SSH="ssh -i ~/.ssh/animecloud_key -o StrictHostKeyChecking=no"
          rsync -az --delete \
            -e "$RSYNC_SSH" \
            --exclude ".git/" \
            --exclude ".github/" \
            --exclude ".env" \
            --exclude "gcs-key.json" \
            --exclude "server.log" \
            --exclude "outbox/" \
            --exclude "private/" \
            --exclude "feedback/" \
            ./  ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/root/anime-cloud/

      - name: Restart service + healthcheck (on server)
        run: |
          ssh -i ~/.ssh/animecloud_key -o StrictHostKeyChecking=no \
            ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} <<'SSH'
          set -euxo pipefail
          systemctl daemon-reload || true
          systemctl restart animecloud
          systemctl --no-pager --full status animecloud | sed -n '1,50p' || true
          # základní kontrola, že web běží lokálně na serveru
          command -v curl >/dev/null 2>&1 && curl -fsS -I http://127.0.0.1:8080/index.html | sed -n '1,12p' || true
          SSH
