name: Deploy to Server

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: {}

concurrency:
  group: deploy-production
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # (Volitelné, ale nevadí mít)
      - name: Checkout (for context)
        uses: actions/checkout@v4

      - name: Add server host key to known_hosts
        run: |
          set -e
          mkdir -p ~/.ssh
          PORT="${{ secrets.SSH_PORT || 22 }}"
          ssh-keyscan -p "$PORT" -H "${{ secrets.SSH_HOST }}" >> ~/.ssh/known_hosts

      - name: SSH to server and deploy
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT || 22 }}
          script_stop: true
          script: |
            set -euo pipefail
            WORKDIR="/root/anime-cloud"
            VENV="/opt/animecloud/venv"
            SERVICE="animecloud"

            # --- FIX dubiózního vlastnictví repa ---
            # (1) případně přenastaví vlastníka na root
            chown -R root:root "$WORKDIR" || true
            # (2) označí adresář jako bezpečný pro git
            git config --global --add safe.directory "$WORKDIR" || true
            # --------------------------------------

            echo "==> Git pull"
            cd "$WORKDIR"
            git fetch --prune origin main
            git reset --hard origin/main

            echo "==> Python venv & deps"
            if [ ! -d "$VENV" ]; then python3 -m venv "$VENV"; fi
            "$VENV/bin/pip" install -U pip
            "$VENV/bin/pip" install -r requirements.txt

            echo "==> Restart service"
            systemctl daemon-reload || true
            systemctl restart "$SERVICE"

            echo "==> Healthcheck"
            for i in {1..10}; do
              curl -fsS -I http://127.0.0.1:8080/index.html >/dev/null 2>&1 && { echo OK; break; }
              echo "Waiting... ($i/10)"; sleep 2
            done

            systemctl --no-pager --full status "$SERVICE" || true
            journalctl -u "$SERVICE" -n 80 --no-pager || true
