name: Deploy

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Add server to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Start ssh-agent and add key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Rsync files to server
        run: |
          rsync -az --delete \
            --exclude '.git' --exclude '.github' \
            ./ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/root/anime-cloud/

      - name: Restart service
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} \
            'systemctl restart animecloud && systemctl --no-pager --full status animecloud | sed -n "1,12p"'
